version: '3.6'

services:
  consul:
    image: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    environment:
      - 'CONSUL_LOCAL_CONFIG={"bootstrap_expect":1,"data_dir":"/usr/local/bin/consul.d/data1","server":true}'
  nikerecordservice:
    image: nike/nikerecordservice
    depends_on:
      - "consul"
    ports:
      - "20011:20011"
    deploy:
      replicas: 2
    environment:
      - 'SPRING_PROFILES_ACTIVE=default,consul'



